repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black ./src/pyextremes --check
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: pylint ./src/pyextremes
        language: system
        always_run: true
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        always_run: true
        pass_filenames: false
