language: python

python:
    - "3.6"
    - "3.7"

install:
    - pip install pipenv
    - pipenv install --dev
    - python setup.py install

script:
    - py.test -v tests --cov=pyextremes --ignore=tests/test_plotting

after_success:
    - codecov
