language: python

python:
    - "3.6"
    - "3.7"

install:
    - pip install pytest pytest-cov codecov numpy pandas scipy matplotlib emcee
    - python setup.py install

script:
    - python -m pytest -v tests --cov=pyextremes --ignore=tests/test_plotting

after_success:
    - codecov
